version: "3.8"

services:
  coqui-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coqui-tts
    ports:
      - "5000:5002"           # Mappa host 5000 → container 5002 (tts-server lyssnar där)
    environment:
      - MODEL_NAME=tts_models/sv/cv/vits
    volumes:
      - coqui_data:/root/.cache/tts   # Cache för nedladdade Coqui-modeller
    restart: unless-stopped

volumes:
  coqui_data:
    driver: local
