version: "3.8"

services:
  coqui-tts:
    image: sepia/coqui-tts:aarch64  # Färdig ARM64‐bild som innehåller Coqui TTS 0.12.x
    container_name: coqui-tts
    ports:
      - "5000:80"                   # Mappa host-port 5000 → containerns port 80
    environment:
      - TTS_MODEL=tts_models/sv/cv/vits
    restart: unless-stopped
