version: "3.8"

services:
  coqui-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coqui-tts
    ports:
      - "5000:5002"            # Mappa host-port 5000 → container-port 5002
    environment:
      - MODEL_NAME=tts_models/sv/cv/vits
    volumes:
      - coqui_data:/root/.cache/tts   # Volym för att spara nedladdade TTS-modeller
    restart: unless-stopped

volumes:
  coqui_data:
    driver: local
